<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="academic.aspx.cs" Inherits="academic" %>

<asp:Content ID="Content1" ContentPlaceHolderID="title" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
    .auto-style1 {
        width: 100%;
    }
    .auto-style2 {
        font-size: x-large;
        color: rgb(0, 102, 0);
    }
</style>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Contentbody" Runat="Server">
    <table class="auto-style1">
    <tr>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>
            <div id="School_for_Children_with_Autism.2FP.D.D." style="box-sizing: border-box; color: rgb(32, 33, 33); font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong><span class="auto-style2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Academic Help</span></strong></div>
            <h2 style="box-sizing: border-box; font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 1.1; color: rgb(97, 136, 55); margin-top: 30px; margin-bottom: 10px; font-size: 22px; padding-bottom: 0.2em; border-bottom: 1px solid rgb(185, 187, 186); padding-top: 10px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span id="School_for_Children_with_Autism/P.D.D." class="mw-headline" style="box-sizing: border-box;">School for Children with Autism/P.D.D.</span></h2>
            <ul style="box-sizing: border-box; margin: auto auto 1em; padding: 0px 0px 0px 1em; list-style-type: disc; list-style-image: url(&quot;data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%0A%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%225%22%20height%3D%2215%22%3E%0A%3Ccircle%20cx%3D%222.5%22%20cy%3D%229.5%22%20r%3D%222.5%22%20fill%3D%22%23202121%22%2F%3E%0A%3C%2Fsvg%3E%0A&quot;); color: rgb(32, 33, 33); font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <li style="box-sizing: border-box;">Special education schools designed for children who have been diagnosed with autism/P.D.D. have at least 4 classes, with 5-8 students in each class.</li>
                <li style="box-sizing: border-box;">Each class is staffed with a special education teacher and an aide.</li>
                <li style="box-sizing: border-box;">Some of these schools are designed for students ages 6-21, while others are only for primary school-age children or high school-age children.</li>
                <li style="box-sizing: border-box;">The school year continues until August 15, and the extended daily schedule ends at 16:45.</li>
                <li style="box-sizing: border-box;">The students are entitled to meals, escorted transportation, paramedical treatments provided by the Ministry of Education (approximately 2.9 hours/week), and more.</li>
                <li style="box-sizing: border-box;"><b style="box-sizing: border-box; font-weight: 600;">A student may only be placed in such a school after a<span>&nbsp;</span><a class="extiw extiw-he" href="https://www.kolzchut.org.il/he/ועדת_השמה" style="box-sizing: border-box; background-color: transparent; color: rgb(32, 33, 33); text-decoration: underline;" title="he:ועדת השמה">placement committee</a><span>&nbsp;</span>has determined that he/she is eligible for a special education framework.</b></li>
            </ul>
            <p style="box-sizing: border-box; margin: 0px 0px 1em; color: rgb(32, 33, 33); font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <br style="box-sizing: border-box;" />
            </p>
            <h2 style="box-sizing: border-box; font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 1.1; color: rgb(97, 136, 55); margin-top: 30px; margin-bottom: 10px; font-size: 22px; padding-bottom: 0.2em; border-bottom: 1px solid rgb(185, 187, 186); padding-top: 10px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span id="Special_Education_School" class="mw-headline" style="box-sizing: border-box;">Special Education School</span></h2>
            <ul style="box-sizing: border-box; margin: auto auto 1em; padding: 0px 0px 0px 1em; list-style-type: disc; list-style-image: url(&quot;data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%0A%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%225%22%20height%3D%2215%22%3E%0A%3Ccircle%20cx%3D%222.5%22%20cy%3D%229.5%22%20r%3D%222.5%22%20fill%3D%22%23202121%22%2F%3E%0A%3C%2Fsvg%3E%0A&quot;); color: rgb(32, 33, 33); font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <li style="box-sizing: border-box;">A school for students with various disorders.</li>
                <li style="box-sizing: border-box;"><b style="box-sizing: border-box; font-weight: 600;">A student may only be placed in such a school after a placement committee has determined that he/she is eligible for a special education framework.</b></li>
                <li style="box-sizing: border-box;">A listing of special education schools according to region, from the Ministry of Education website:<span>&nbsp;</span><a class="external text" href="http://cms.education.gov.il/EducationCMS/Units/Special/Misgerot/Reshima.htm#8" rel="noreferrer noopener" style="box-sizing: border-box; background-color: transparent; color: rgb(32, 33, 33); text-decoration: underline; background-position: right center; background-repeat: no-repeat; background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKAgMAAADwXCcuAAAACVBMVEUAAABihzSDlmrT30TmAAAAAXRSTlMAQObYZgAAAC9JREFUCNdjYAgNYGByEGBgCBBgCE0QYHDsFGBwUw1g8JjSwODkwsDgwAJUEsIAAH55BoFi6jBjAAAAAElFTkSuQmCC&quot;); padding-right: 13px;" target="_blank">Southern Region</a>,<span>&nbsp;</span><a class="external text" href="http://cms.education.gov.il/EducationCMS/Units/Special/Misgerot/Reshima.htm#5" rel="noreferrer noopener" style="box-sizing: border-box; background-color: transparent; color: rgb(32, 33, 33); text-decoration: underline; background-position: right center; background-repeat: no-repeat; background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKAgMAAADwXCcuAAAACVBMVEUAAABihzSDlmrT30TmAAAAAXRSTlMAQObYZgAAAC9JREFUCNdjYAgNYGByEGBgCBBgCE0QYHDsFGBwUw1g8JjSwODkwsDgwAJUEsIAAH55BoFi6jBjAAAAAElFTkSuQmCC&quot;); padding-right: 13px;" target="_blank">Haifa 
                    Region</a>,<span>&nbsp;</span><a class="external text" href="http://cms.education.gov.il/EducationCMS/Units/Special/Misgerot/Reshima.htm#4" rel="noreferrer noopener" style="box-sizing: border-box; background-color: transparent; color: rgb(32, 33, 33); text-decoration: underline; background-position: right center; background-repeat: no-repeat; background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKAgMAAADwXCcuAAAACVBMVEUAAABihzSDlmrT30TmAAAAAXRSTlMAQObYZgAAAC9JREFUCNdjYAgNYGByEGBgCBBgCE0QYHDsFGBwUw1g8JjSwODkwsDgwAJUEsIAAH55BoFi6jBjAAAAAElFTkSuQmCC&quot;); padding-right: 13px;" target="_blank">Central Region</a>,<span>&nbsp;</span><a class="external text" href="http://cms.education.gov.il/EducationCMS/Units/Special/Misgerot/Reshima.htm#6" rel="noreferrer noopener" style="box-sizing: border-box; background-color: transparent; color: rgb(32, 33, 33); text-decoration: underline; background-position: right center; background-repeat: no-repeat; background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKAgMAAADwXCcuAAAACVBMVEUAAABihzSDlmrT30TmAAAAAXRSTlMAQObYZgAAAC9JREFUCNdjYAgNYGByEGBgCBBgCE0QYHDsFGBwUw1g8JjSwODkwsDgwAJUEsIAAH55BoFi6jBjAAAAAElFTkSuQmCC&quot;); padding-right: 13px;" target="_blank">Northern 
                    Region</a>,<span>&nbsp;</span><a class="external text" href="http://cms.education.gov.il/EducationCMS/Units/Special/Misgerot/Reshima.htm#3" rel="noreferrer noopener" style="box-sizing: border-box; background-color: transparent; color: rgb(32, 33, 33); text-decoration: underline; background-position: right center; background-repeat: no-repeat; background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKAgMAAADwXCcuAAAACVBMVEUAAABihzSDlmrT30TmAAAAAXRSTlMAQObYZgAAAC9JREFUCNdjYAgNYGByEGBgCBBgCE0QYHDsFGBwUw1g8JjSwODkwsDgwAJUEsIAAH55BoFi6jBjAAAAAElFTkSuQmCC&quot;); padding-right: 13px;" target="_blank">Tel Aviv Region</a>,<span>&nbsp;</span><a class="external text" href="http://cms.education.gov.il/EducationCMS/Units/Special/Misgerot/Reshima.htm#1" rel="noreferrer noopener" style="box-sizing: border-box; background-color: transparent; color: rgb(32, 33, 33); text-decoration: underline; background-position: right center; background-repeat: no-repeat; background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKAgMAAADwXCcuAAAACVBMVEUAAABihzSDlmrT30TmAAAAAXRSTlMAQObYZgAAAC9JREFUCNdjYAgNYGByEGBgCBBgCE0QYHDsFGBwUw1g8JjSwODkwsDgwAJUEsIAAH55BoFi6jBjAAAAAElFTkSuQmCC&quot;); padding-right: 13px;" target="_blank">Jerusalem 
                    Region and Jerusalem Education Authority</a>.</li>
            </ul>
            <h2 style="box-sizing: border-box; font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 1.1; color: rgb(97, 136, 55); margin-top: 30px; margin-bottom: 10px; font-size: 22px; padding-bottom: 0.2em; border-bottom: 1px solid rgb(185, 187, 186); padding-top: 10px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span id="Communication_Class" class="mw-headline" style="box-sizing: border-box;">Communication Class</span></h2>
            <ul style="box-sizing: border-box; margin: auto auto 1em; padding: 0px 0px 0px 1em; list-style-type: disc; list-style-image: url(&quot;data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%0A%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%225%22%20height%3D%2215%22%3E%0A%3Ccircle%20cx%3D%222.5%22%20cy%3D%229.5%22%20r%3D%222.5%22%20fill%3D%22%23202121%22%2F%3E%0A%3C%2Fsvg%3E%0A&quot;); color: rgb(32, 33, 33); font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <li style="box-sizing: border-box;">Special education classes located in regular schools, which are designed for children who have been diagnosed with autism/P.D.D.</li>
                <li style="box-sizing: border-box;">Between 5-8 students are in each class.</li>
                <li style="box-sizing: border-box;">Each class is staffed with a special education teacher and an aide.</li>
                <li style="box-sizing: border-box;">The school year continues until August 15 (except for middle school and high school which continue until August 5), and the extended daily schedule ends at 16:45.</li>
                <li style="box-sizing: border-box;">The students are entitled to meals, escorted transportation, paramedical treatments provided by the Ministry of Education (approximately 2.9 hours/week), and more.</li>
                <li style="box-sizing: border-box;">A personalized educational plan is prepared at the beginning of the year for each communication class student.</li>
                <li style="box-sizing: border-box;"><b style="box-sizing: border-box; font-weight: 600;">In order to request placement in a communication class, the local authority’s education office must be contacted and a request for a placement committee hearing must be submitted.</b></li>
            </ul>
            <h2 style="box-sizing: border-box; font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 1.1; color: rgb(97, 136, 55); margin-top: 30px; margin-bottom: 10px; font-size: 22px; padding-bottom: 0.2em; border-bottom: 1px solid rgb(185, 187, 186); padding-top: 10px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span id="Individual_Integration_in_a_Regular_School" class="mw-headline" style="box-sizing: border-box;">Individual Integration in a Regular School</span></h2>
            <ul style="box-sizing: border-box; margin: auto auto 1em; padding: 0px 0px 0px 1em; list-style-type: disc; list-style-image: url(&quot;data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%0A%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%225%22%20height%3D%2215%22%3E%0A%3Ccircle%20cx%3D%222.5%22%20cy%3D%229.5%22%20r%3D%222.5%22%20fill%3D%22%23202121%22%2F%3E%0A%3C%2Fsvg%3E%0A&quot;); color: rgb(32, 33, 33); font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <li style="box-sizing: border-box;">Some children may be<span>&nbsp;</span><a class="extiw extiw-he" href="https://www.kolzchut.org.il/he/שילוב_ילדים_עם_צרכים_מיוחדים_במערכת_החינוך_הרגילה" style="box-sizing: border-box; background-color: transparent; color: rgb(32, 33, 33); text-decoration: underline;" title="he:שילוב ילדים עם צרכים מיוחדים במערכת החינוך הרגילה">individually integrated</a><span>&nbsp;</span>into a regular classroom setting.</li>
                <li style="box-sizing: border-box;">In addition to the classroom teacher, there is also an integration aide who is responsible for integrating the student into the class and accompanying the student between 7-30 hours per week according to the student’s functioning capacity.</li>
                <li style="box-sizing: border-box;">Additionally, each child is entitled to an integration basket, which includes remedial instruction, creative and expressive therapy, paramedical treatments, instruction from the treatment staff, and more.</li>
                <li style="box-sizing: border-box;"><b style="box-sizing: border-box; font-weight: 600;">In order to be integrated into a regular school, register the child for the school and then contact the school principal to request an<span>&nbsp;</span><a class="extiw extiw-he" href="https://www.kolzchut.org.il/he/ועדת_שילוב" style="box-sizing: border-box; background-color: transparent; color: rgb(32, 33, 33); text-decoration: underline;" title="he:ועדת שילוב">integration committee</a><span>&nbsp;</span>hearing.</b></li>
                <li style="box-sizing: border-box;">See recommendations for parents involved in integration of their children on the<span>&nbsp;</span><a class="external text" href="http://alut.org.il/wp-content/uploads/2014/05/shiluv_yechdani_recommendation.pdf" rel="noreferrer noopener" style="box-sizing: border-box; background-color: transparent; color: rgb(32, 33, 33); text-decoration: underline; background-position: right center; background-repeat: no-repeat; background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKAgMAAADwXCcuAAAACVBMVEUAAABihzSDlmrT30TmAAAAAXRSTlMAQObYZgAAAC9JREFUCNdjYAgNYGByEGBgCBBgCE0QYHDsFGBwUw1g8JjSwODkwsDgwAJUEsIAAH55BoFi6jBjAAAAAElFTkSuQmCC&quot;); padding-right: 13px;" target="_blank">information page</a><span>&nbsp;</span>of ALUT.</li>
                <li style="box-sizing: border-box;">
                    <h2 style="box-sizing: border-box; font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 1.1; color: rgb(97, 136, 55); margin-top: 30px; margin-bottom: 10px; font-size: 22px; padding-bottom: 0.2em; border-bottom: 1px solid rgb(185, 187, 186); padding-top: 10px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span id="Aid_organizations" class="mw-headline" style="box-sizing: border-box;">Aid organizations</span></h2>
                    <ul style="box-sizing: border-box; margin: auto auto 1em; padding: 0px 0px 0px 1em; list-style-type: disc; list-style-image: url(&quot;data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%0A%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%225%22%20height%3D%2215%22%3E%0A%3Ccircle%20cx%3D%222.5%22%20cy%3D%229.5%22%20r%3D%222.5%22%20fill%3D%22%23202121%22%2F%3E%0A%3C%2Fsvg%3E%0A&quot;); color: rgb(32, 33, 33); font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                        <li style="box-sizing: border-box;"><a class="extiw extiw-he" href="https://www.kolzchut.org.il/he/אלו%22ט" style="box-sizing: border-box; background-color: transparent; color: rgb(32, 33, 33); text-decoration: underline;" title="he:אלו&quot;ט">ALUT</a></li>
                        <li style="box-sizing: border-box;"><a class="extiw extiw-he" href="https://www.kolzchut.org.il/he/העמותה_לילדים_בסיכון" style="box-sizing: border-box; background-color: transparent; color: rgb(32, 33, 33); text-decoration: underline;" title="he:העמותה לילדים בסיכון">Association for Children at Risk</a></li>
                        <li style="box-sizing: border-box;"><a class="extiw extiw-he" href="https://www.kolzchut.org.il/he/ועד_ההורים_המשלבים_הארצי_לילדים_עם_אוטיזם" style="box-sizing: border-box; background-color: transparent; color: rgb(32, 33, 33); text-decoration: underline;" title="he:ועד ההורים המשלבים הארצי לילדים עם אוטיזם">National Parents Committee for the Integration of Children with Autism</a></li>
                    </ul>
                    <h2 style="box-sizing: border-box; font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 1.1; color: rgb(97, 136, 55); margin-top: 30px; margin-bottom: 10px; font-size: 22px; padding-bottom: 0.2em; border-bottom: 1px solid rgb(185, 187, 186); padding-top: 10px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span id="Government_agencies" class="mw-headline" style="box-sizing: border-box;">Government agencies</span></h2>
                    <ul style="box-sizing: border-box; margin: auto auto 1em; padding: 0px 0px 0px 1em; list-style-type: disc; list-style-image: url(&quot;data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%0A%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%225%22%20height%3D%2215%22%3E%0A%3Ccircle%20cx%3D%222.5%22%20cy%3D%229.5%22%20r%3D%222.5%22%20fill%3D%22%23202121%22%2F%3E%0A%3C%2Fsvg%3E%0A&quot;); color: rgb(32, 33, 33); font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                        <li style="box-sizing: border-box;"><a class="extiw extiw-he" href="https://www.kolzchut.org.il/he/משרד_החינוך" style="box-sizing: border-box; background-color: transparent; color: rgb(32, 33, 33); text-decoration: underline;" title="he:משרד החינוך">The Ministry of Education</a></li>
                    </ul>
                    <div id="Laws_.26_Regulations" style="box-sizing: border-box; color: rgb(32, 33, 33); font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    </div>
                    <h2 style="box-sizing: border-box; font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 1.1; color: rgb(97, 136, 55); margin-top: 30px; margin-bottom: 10px; font-size: 22px; padding-bottom: 0.2em; border-bottom: 1px solid rgb(185, 187, 186); padding-top: 10px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span id="Laws_Regulations" class="mw-headline" style="box-sizing: border-box;">Laws &amp; Regulations</span></h2>
                    <ul style="box-sizing: border-box; margin: auto auto 1em; padding: 0px 0px 0px 1em; list-style-type: disc; list-style-image: url(&quot;data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%0A%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%225%22%20height%3D%2215%22%3E%0A%3Ccircle%20cx%3D%222.5%22%20cy%3D%229.5%22%20r%3D%222.5%22%20fill%3D%22%23202121%22%2F%3E%0A%3C%2Fsvg%3E%0A&quot;); color: rgb(32, 33, 33); font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                        <li style="box-sizing: border-box;"><a class="extiw extiw-he" href="https://www.kolzchut.org.il/he/חוק_חינוך_מיוחד" style="box-sizing: border-box; background-color: transparent; color: rgb(32, 33, 33); text-decoration: underline;" title="he:חוק חינוך מיוחד">Special Education Law</a></li>
                    </ul>
                    <h2 style="box-sizing: border-box; font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 1.1; color: rgb(97, 136, 55); margin-top: 30px; margin-bottom: 10px; font-size: 22px; padding-bottom: 0.2em; border-bottom: 1px solid rgb(185, 187, 186); padding-top: 10px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span id="Additional_Publications" class="mw-headline" style="box-sizing: border-box;">Additional Publications</span></h2>
                    <p style="box-sizing: border-box; margin: 0px 0px 1em; color: rgb(32, 33, 33); font-family: Assistant, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                        <a class="external text" href="http://www.alut.org.il/download/files/hebrew_social_benefits_children_feb2012_1071.pdf" rel="noreferrer noopener" style="box-sizing: border-box; background-color: transparent; color: rgb(32, 33, 33); text-decoration: underline; background-position: right center; background-repeat: no-repeat; background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKAgMAAADwXCcuAAAACVBMVEUAAABihzSDlmrT30TmAAAAAXRSTlMAQObYZgAAAC9JREFUCNdjYAgNYGByEGBgCBBgCE0QYHDsFGBwUw1g8JjSwODkwsDgwAJUEsIAAH55BoFi6jBjAAAAAElFTkSuQmCC&quot;); padding-right: 13px;" target="_blank">Booklet of Rights for Children on the Autism Spectrum</a>.</p>
                </li>
            </ul>
        </td>
    </tr>
</table>
</asp:Content>

