<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="achievement.aspx.cs" Inherits="achievement" %>

<asp:Content ID="Content1" ContentPlaceHolderID="title" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            width: 346px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Contentbody" Runat="Server">
    <table class="auto-style1">
        <tr>
            <td>
                <table class="auto-style1">
                    <tr>
                        <td class="auto-style2">
                            <img alt="Autism Quote 1" src="http://blog.autismtreatmentcenter.org/wp-content/uploads/2016/08/AutismQuote1-1.jpg" style="height: 526px; width: 343px" /></td>
                        <td>
                            <img alt="Autism Quote 2" src="http://blog.autismtreatmentcenter.org/wp-content/uploads/2016/08/AutismQuote2.jpg" style="height: 526px; width: 339px" /></td>
                        <td>&nbsp;</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                <article id="post-993" class="et_pb_post clearfix et_pb_no_thumb post-993 post type-post status-publish format-standard hentry category-achievements" style="box-sizing: border-box; display: block; word-wrap: break-word; margin-bottom: 60px; font-family: Comfortaa, cursive !important; position: relative; color: rgb(102, 102, 102); font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <h2 class="entry-title" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 10px; border: 0px; outline: 0px; background: 0px 0px; font-size: 26px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(51, 51, 51); font-weight: 500; line-height: 1em; font-family: Comfortaa, cursive !important;"><a href="https://www.forumforautism.org/asd-individual-describes-work-experience-cisco/" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 26px; vertical-align: baseline; text-size-adjust: 100%; color: inherit; text-decoration: none;">An ASD individual describes his work experience at CISCO</a></h2>
                    <div class="post-content" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%;">
                        <p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(102, 102, 102);">
                            Sky is the limit when it comes to the accomplishments of individuals with autism !! One of them who works at CISCO describes his...</p>
                        <a class="more-link" href="https://www.forumforautism.org/asd-individual-describes-work-experience-cisco/" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(46, 163, 242); text-decoration: none; display: block; clear: both;">read more</a></div>
                </article>
                <article id="post-886" class="et_pb_post clearfix et_pb_no_thumb post-886 post type-post status-publish format-standard hentry category-achievements" style="box-sizing: border-box; display: block; word-wrap: break-word; margin-bottom: 60px; font-family: Comfortaa, cursive !important; position: relative; color: rgb(102, 102, 102); font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <h2 class="entry-title" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 10px; border: 0px; outline: 0px; background: 0px 0px; font-size: 26px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(51, 51, 51); font-weight: 500; line-height: 1em; font-family: Comfortaa, cursive !important;"><a href="https://www.forumforautism.org/varun-sawant-completed-marathon-waad/" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 26px; vertical-align: baseline; text-size-adjust: 100%; color: inherit; text-decoration: none;">Varun Sawant completed marathon on WAAD</a></h2>
                    <div class="post-content" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%;">
                        <p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(102, 102, 102);">
                            Varun Sawant completed the marathon on the occasion of World Autism Awareness...</p>
                        <a class="more-link" href="https://www.forumforautism.org/varun-sawant-completed-marathon-waad/" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(46, 163, 242); text-decoration: none; display: block; clear: both;">read more</a></div>
                </article>
                <article id="post-881" class="et_pb_post clearfix et_pb_no_thumb post-881 post type-post status-publish format-standard hentry category-achievements" style="box-sizing: border-box; display: block; word-wrap: break-word; margin-bottom: 60px; font-family: Comfortaa, cursive !important; position: relative; color: rgb(102, 102, 102); font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <h2 class="entry-title" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 10px; border: 0px; outline: 0px; background: 0px 0px; font-size: 26px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(51, 51, 51); font-weight: 500; line-height: 1em; font-family: Comfortaa, cursive !important;"><a href="https://www.forumforautism.org/deepthi-ganesh-86-girl-autism-tops-college/" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 26px; vertical-align: baseline; text-size-adjust: 100%; color: inherit; text-decoration: none;">Deepthi Ganesh: With 86%, girl with autism tops college</a></h2>
                    <div class="post-content" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%;">
                        <p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(102, 102, 102);">
                            Deepthi Ganesh, a student of Hemu Kalani Junior College, has proved that autism cannot hold her back. Deepthi, who scored 85.8% in the HSC vocational stream, has topped her...</p>
                        <a class="more-link" href="https://www.forumforautism.org/deepthi-ganesh-86-girl-autism-tops-college/" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(46, 163, 242); text-decoration: none; display: block; clear: both;">read more</a></div>
                </article>
                <article id="post-877" class="et_pb_post clearfix et_pb_no_thumb post-877 post type-post status-publish format-standard hentry category-achievements" style="box-sizing: border-box; display: block; word-wrap: break-word; margin-bottom: 60px; font-family: Comfortaa, cursive !important; position: relative; color: rgb(102, 102, 102); font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <h2 class="entry-title" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 10px; border: 0px; outline: 0px; background: 0px 0px; font-size: 26px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(51, 51, 51); font-weight: 500; line-height: 1em; font-family: Comfortaa, cursive !important;"><a href="https://www.forumforautism.org/aditya-rao-sabrish-sriram-city-boys-set-aside-hurdles-ace-hsc/" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 26px; vertical-align: baseline; text-size-adjust: 100%; color: inherit; text-decoration: none;">Aditya Rao, Sabrish Sriram: City boys set aside hurdles to ace HSC</a></h2>
                    <div class="post-content" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%;">
                        <p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(102, 102, 102);">
                            Children with Autism Spectrum Disorder from the city made their parents proud by excelling in HSC examination conducted by the Maharashtra State Board of Secondary and Higher Secondary...</p>
                        <a class="more-link" href="https://www.forumforautism.org/aditya-rao-sabrish-sriram-city-boys-set-aside-hurdles-ace-hsc/" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(46, 163, 242); text-decoration: none; display: block; clear: both;">read more</a></div>
                </article>
                <article id="post-872" class="et_pb_post clearfix et_pb_no_thumb post-872 post type-post status-publish format-standard hentry category-achievements" style="box-sizing: border-box; display: block; word-wrap: break-word; margin-bottom: 60px; font-family: Comfortaa, cursive !important; position: relative; color: rgb(102, 102, 102); font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <h2 class="entry-title" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 10px; border: 0px; outline: 0px; background: 0px 0px; font-size: 26px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(51, 51, 51); font-weight: 500; line-height: 1em; font-family: Comfortaa, cursive !important;"><a href="https://www.forumforautism.org/nehal-tiwari-autism-no-barrier-pass-flying-colours/" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 26px; vertical-align: baseline; text-size-adjust: 100%; color: inherit; text-decoration: none;">Nehal Tiwari: Autism no barrier for her to pass with flying colours</a></h2>
                    <div class="post-content" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%;">
                        <p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(102, 102, 102);">
                            Nehal Tiwari, a science student of Gopi Birla School, Walkeshwar, has more to be proud of than her board examination score. Nehal, who suffers from Autism Spectrum Disorder, has secured...</p>
                        <a class="more-link" href="https://www.forumforautism.org/nehal-tiwari-autism-no-barrier-pass-flying-colours/" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(46, 163, 242); text-decoration: none; display: block; clear: both;">read more</a></div>
                </article>
                <article id="post-656" class="et_pb_post clearfix et_pb_no_thumb post-656 post type-post status-publish format-standard hentry category-achievements" style="box-sizing: border-box; display: block; word-wrap: break-word; margin-bottom: 60px; font-family: Comfortaa, cursive !important; position: relative; color: rgb(102, 102, 102); font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <h2 class="entry-title" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 10px; border: 0px; outline: 0px; background: 0px 0px; font-size: 26px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(51, 51, 51); font-weight: 500; line-height: 1em; font-family: Comfortaa, cursive !important;"><a href="https://www.forumforautism.org/children-with-asd-pass-ssc-with-flying-colours/" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 26px; vertical-align: baseline; text-size-adjust: 100%; color: inherit; text-decoration: none;">Children with ASD pass SSC with flying colours</a></h2>
                    <div class="post-content" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%;">
                        <p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(102, 102, 102);">
                            Usaid Sheikh, from Yashodham High School, Goregaon, an autistic child, scored 90.2%. “His principal and others from school have been extremely supportive.” said his mother Fatima. He plans to pursue computers, art or music. Advait Gangakhedkhar,16, also an autistic...</p>
                        <a class="more-link" href="https://www.forumforautism.org/children-with-asd-pass-ssc-with-flying-colours/" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; background: 0px 0px; font-size: 14px; vertical-align: baseline; text-size-adjust: 100%; color: rgb(46, 163, 242); text-decoration: none; display: block; clear: both;">read more</a></div>
                </article>
            </td>
        </tr>
    </table>
</asp:Content>

