<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="club.aspx.cs" Inherits="club" %>

<asp:Content ID="Content1" ContentPlaceHolderID="title" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            color: rgb(0, 102, 255);
        }
        .auto-style3 {
            color: rgb(0, 153, 51);
        }
    </style>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Contentbody" Runat="Server">
    <table class="auto-style1">
        <tr>
            <td>
                <img alt="Image result for activities and clubs for autistic children" src="http://cdn.sandals.com/beaches/v11/site-elements/activities/kidscamp-banner.jpg" style="width: 1486px" /></td>
        </tr>
        <tr>
            <td>
                <img alt="" src="https://www.autismspeaks.org/sites/default/files/images/family-services/d_200907_swimming.jpg.jpg" style="border: 0px; max-width: 100%; height: 130px; display: block; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; width: 180px; margin: 10px; float: left;" /><p class="auto-style2" style="margin: 1em auto; text-align: left !important; font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong>Recreation is about activities and experiences which produce feelings of enjoyment and satisfaction. They give all of us opportunities to express creativity, achieve and master new skills. Recreation can be particularly important for people with autism, drawing on opportunities to practice social skills, physical aptitude and increase motivation. These activities can provide the basis for increased self-confidence for your child. Participation in recreation and leisure activities allows individuals with autism to learn skills specific to a particular sport or activity. But more importantly, participation in these programs also helps improve more general skills that can be applied in settings like school and work. So progress can be seen not just in the specific programs, but in other areas of life as well.</strong></p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    &nbsp;</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">The Benefits Outweigh the Effort it Takes to Put it Together!</strong></p>
                <ul class="auto-style3" style="margin: 1em 0px; padding: 0px 0px 0px 40px; font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <li>Recreation is important in promoting inclusion and quality of life.</li>
                    <li>Increases self-esteem and confidence.</li>
                    <li>Gives people the opportunity to make their own choices.</li>
                    <li>Provides satisfaction, enjoyment and pleasure.</li>
                    <li>Enables individuals with autism to become involved and feel like a part of their community.</li>
                    <li>Provides the opportunity to gain and develop new contacts and friends.</li>
                    <li>Sports and exercise programs can improve physical and mental health.</li>
                    <li>Reduces reliance on parents and other adults.</li>
                    <li>Increases independence which leads to increased opportunities.</li>
                </ul>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;"><span class="auto-style3">Three Frequently Asked Questions about Recreation for Individuals on the Spec</span>trum</strong></p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    1)<span>&nbsp;</span><strong style="font-weight: bold;"><em>How do I figure out what my child enjoys?</em></strong></p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Work within the context of a your child&#39;s skills and interests. Exposure, exposure, exposure! Give your child the opportunity to try multiple activities for a period of time to see if something particular clicks with them. Children might have limited interests, so getting them involved in recreational activities can sometimes require expanding traditional ideas of leisure. Often times, leisure skills must be specifically taught to individuals with autism. Teaching these skills to your children will increase their confidence and as a result make them more interested in joining recreational programs, clubs or teams. You can also use technology to help you figure it out. The Wii system provides sporting activity simulations that can bridge the gap between your child&#39;s interest in video games and real world activities.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    2)<span>&nbsp;</span><strong style="font-weight: bold;"><em>How do I deal with a situation involving recreation that goes bad?</em></strong></p>
                <img alt="" src="https://www.autismspeaks.org/sites/default/files/images/family-services/d_200907_run.jpg" style="border: 0px; max-width: 100%; height: 114px; display: block; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; width: 209px; margin: 10px; float: right;" /><p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    No matter how much you want a recreational activity to work, there is always the chance that it won&#39;t. You may run into difficult or uncomfortable situations that you cannot change. Planning ahead and being prepared with an alternate plan is important. You may not get the support you need to fully integrate your son/daughter at the local YMCA swim team, but another plan might be to have your child and a sibling set up races that allow both kids to feel successful.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Receiving support from other parents of children with autism who have similar experiences can also be incredibly helpful. You can offer each other suggestions about what has worked for you and before long, you could be laughing about an experience gone bad that only a day before was upsetting to you. Visit the<span>&nbsp;</span><a href="http://autismspeaksnetwork.ning.com/" style="color: rgb(40, 65, 119); text-decoration: underline;" target="_blank">Autism Speaks Social Network</a><span>&nbsp;</span>to connect with other parents of children with autism.</p>
                <img alt="" src="https://www.autismspeaks.org/sites/default/files/images/family-services/d_200907_camping.jpg" style="border: 0px; max-width: 100%; height: 114px; display: block; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; width: 209px; margin: 10px; float: left;" /><p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    3)<span>&nbsp;</span><strong style="font-weight: bold;"><em>What are some examples of recreational activities that young people with autism might enjoy?</em></strong><br />
                    The social component of some recreational and leisure activities might make some activities more fulfilling and enjoyable for your children with autism.</p>
                <ul style="margin: 1em 0px; padding: 0px 0px 0px 40px; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <li>Hobbies such as collecting stamps, playing cards or board games, drawing and photography can also provide opportunities for enjoyment, as well as increased self-confidence and motivation individuals on the spectrum.</li>
                    <li>Individual sporting activities such as Track, Skiing, Hiking, Golf, Cycling, or Cross-Country allow individuals with autism to participate in recreation without social interactions that might cause stress.</li>
                    <li>Some communities have autism-specific sports teams that can provide the support your child needs to participate in a team sport like baseball or hockey. For more information, visit the<span>&nbsp;</span><a href="http://www.americanspecialhockey.org/" style="color: rgb(40, 65, 119); text-decoration: underline;" target="_blank">American Special Hockey Association</a><span>&nbsp;</span>or the<span>&nbsp;</span><a href="http://www.allplay.org/" style="color: rgb(40, 65, 119); text-decoration: underline;" target="_blank">All Play Miracle Baseball League</a>.</li>
                </ul>
                <img alt="" src="https://www.autismspeaks.org/sites/default/files/images/family-services/d_200907_goggles.jpg.jpg" style="border: 0px; max-width: 100%; height: 144px; display: block; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; width: 180px; margin: 10px; float: left;" /><p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Recreation Grants Funded by Autism Speaks</strong></p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Click<span>&nbsp;</span><a href="https://www.autismspeaks.org/sites/default/files/documents/family-services/recgrants.pdf" style="color: rgb(40, 65, 119); text-decoration: underline;" target="_blank">here</a><span>&nbsp;</span>for a list of the recreational programs that have been funded through Autism Speaks Family Services Community Grants. Community Grants fund a wide range of activities from rock climbing, to golf, to theater groups. These organizations can also be useful in giving you ideas about what activities might be a good fit for your child.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <i>Autism Speaks invites service providers who provide Recreation Activities to submit applications for these Family Services Community Grants. Have you been thinking about starting a local activity but need more information? We invite you to contact our grantees to ask questions.</i></p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    We hope this inspires you to be innovative and think outside the box when it comes to recreation!</p>
                <img alt="" src="https://www.autismspeaks.org/sites/default/files/images/family-services/d_200907_club.jpg.jpg" style="border: 0px; max-width: 100%; height: 144px; display: block; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; width: 180px; margin: 10px; float: right;" /><p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Where to Get Help?</strong></p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Recreation therapists, also referred to as therapeutic recreation specialists, provide treatment services and recreation activities for individuals with disabilities. Using a variety of techniques, including arts and crafts, animals, sports, games, dance and movement, drama, music and community outings, therapists improve and maintain the physical, mental and emotional well-being of their clients. Recreation therapists can also help individuals reduce depression, stress and anxiety, build confidence, and socialize effectively so that they can enjoy greater independence. In addition, therapists help people with disabilities integrate into the community by teaching them how to use community resources and participate in recreational activities.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Click<span>&nbsp;</span><a href="http://www.recreationtherapy.com/trorg.htm" style="color: rgb(40, 65, 119); text-decoration: underline;" target="_blank">here</a><span>&nbsp;</span>for a list of recreational therapist organizations to help you find one in your area.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Visit Our Resource Guide!</strong></p>
                <img alt="" src="https://www.autismspeaks.org/sites/default/files/images/family-services/d_200907_mess.jpg.jpg" style="border: 0px; max-width: 100%; height: 171px; display: block; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; float: right; width: 128px; margin: 10px;" /><p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    &nbsp;</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    There are a number of great programs listed in our Resource Guide that vary from athletic to creative, one-on-one instruction to full inclusion, and recreational to competitive. Search<span>&nbsp;</span><a href="https://www.autismspeaks.org/community/fsdb/search.php?chgst=true" style="color: rgb(40, 65, 119); text-decoration: underline;" target="_blank">here</a><span>&nbsp;</span>for programs available in your area. Recreation and Community Activities are specifically for children, while Recreation and Leisure Activities also include adults.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Tell Us About Your Experience!</strong></p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <i>We would like to hear from you! Describe your best experience with a community/recreation group and how you found it. E-mail us at<span>&nbsp;</span></i><a href="mailto:familyservices@autismspeaks.org" style="color: rgb(40, 65, 119); text-decoration: underline;"><i>familyservices@autismspeaks.org</i></a></p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    &nbsp;</p>
            </td>
        </tr>
    </table>
</asp:Content>

