<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="history.aspx.cs" Inherits="history" %>

<asp:Content ID="Content1" ContentPlaceHolderID="title" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
    .auto-style1 {
        width: 100%;
    }
</style>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Contentbody" Runat="Server">
    <table class="auto-style1">
    <tr>
        <td>
            <div class="relatedContentCarousel__item story" style="box-sizing: inherit; border: 0px solid rgb(217, 217, 217); padding: 15px 15px 10px; min-height: 0px !important; flex: 0 0 33.3333%; color: rgb(34, 34, 34); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <div class="relatedContentCarousel__itemWrapper" style="box-sizing: inherit;">
                    <a class="relatedContentCarousel__imageLink" href="https://www.parents.com/health/autism/symptoms/understanding-aspergers-syndrome/" style="box-sizing: inherit; background-color: transparent; color: rgb(0, 163, 185); text-decoration: none; display: block;">
                    <img class="relatedContentCarousel__image" src="https://images.parents.mdpcdn.com/sites/parents.com/files/styles/week_by_week_card/public/images/p_101873314.jpg" style="box-sizing: inherit; border: 0px; max-width: 100%; height: auto; display: inline-block; vertical-align: middle;" /></a><div class="relatedContentCarousel__metaWrapper" style="box-sizing: inherit; margin-top: 0.5rem;">
                        <span class="relatedContentCarousel__heading" style="box-sizing: inherit; font-size: 21px; line-height: 25px; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; max-height: 75px; overflow: hidden; text-overflow: ellipsis; text-align: center;"><a class="relatedContentCarousel__headingLink" href="https://www.parents.com/health/autism/symptoms/understanding-aspergers-syndrome/" style="box-sizing: inherit; background-color: transparent; color: rgb(0, 0, 0); text-decoration: none; font-weight: 700;">The ABCs of Asperger&#39;s Syndrome: An A-to-Z Guide to Understanding the Symptoms of Asperger&#39;s</a></span></div>
                </div>
            </div>
            <div class="relatedContentCarousel__item story" style="box-sizing: inherit; border: 0px solid rgb(217, 217, 217); padding: 15px 15px 10px; min-height: 0px !important; flex: 0 0 33.3333%; color: rgb(34, 34, 34); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <div class="relatedContentCarousel__itemWrapper" style="box-sizing: inherit;">
                    <a class="relatedContentCarousel__imageLink" href="https://www.parents.com/baby/health/autism/autism-month-by-month-guide/" style="box-sizing: inherit; background-color: transparent; color: rgb(0, 163, 185); text-decoration: none; display: block;">
                    <img class="relatedContentCarousel__image" src="https://images.parents.mdpcdn.com/sites/parents.com/files/styles/week_by_week_card/public/images/p_101901470.jpg" style="box-sizing: inherit; border: 0px; max-width: 100%; height: auto; display: inline-block; vertical-align: middle;" /></a><div class="relatedContentCarousel__metaWrapper" style="box-sizing: inherit; margin-top: 0.5rem;">
                        <span class="relatedContentCarousel__heading" style="box-sizing: inherit; font-size: 21px; line-height: 25px; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; max-height: 75px; overflow: hidden; text-overflow: ellipsis; text-align: center;"><a class="relatedContentCarousel__headingLink" href="https://www.parents.com/baby/health/autism/autism-month-by-month-guide/" style="box-sizing: inherit; background-color: transparent; color: rgb(0, 0, 0); text-decoration: none; font-weight: 700;">Autism Signs: Your Month-by-Month Guide</a></span></div>
                </div>
            </div>
            <div class="relatedContentCarousel__item story" style="box-sizing: inherit; border: 0px solid rgb(217, 217, 217); padding: 15px 15px 10px; min-height: 0px !important; flex: 0 0 33.3333%; color: rgb(34, 34, 34); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <div class="relatedContentCarousel__itemWrapper" style="box-sizing: inherit;">
                    <a class="relatedContentCarousel__imageLink" href="https://www.parents.com/health/autism/facts/6-facts-you-need-to-know-about-autism/" style="box-sizing: inherit; background-color: transparent; color: rgb(0, 163, 185); text-decoration: none; display: block;">
                    <img class="relatedContentCarousel__image" src="https://images.parents.mdpcdn.com/sites/parents.com/files/styles/week_by_week_card/public/shutterstock_524440990.jpg" style="box-sizing: inherit; border: 0px; max-width: 100%; height: auto; display: inline-block; vertical-align: middle;" /></a><div class="relatedContentCarousel__metaWrapper" style="box-sizing: inherit; margin-top: 0.5rem;">
                        <span class="relatedContentCarousel__heading" style="box-sizing: inherit; font-size: 21px; line-height: 25px; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; max-height: 75px; overflow: hidden; text-overflow: ellipsis; text-align: center;"><a class="relatedContentCarousel__headingLink" href="https://www.parents.com/health/autism/facts/6-facts-you-need-to-know-about-autism/" style="box-sizing: inherit; background-color: transparent; color: rgb(0, 0, 0); text-decoration: none; font-weight: 700;">6 Facts You Need to Know About Autism</a></span></div>
                </div>
            </div>
            <div class="relatedContentCarousel__item story" style="box-sizing: inherit; border: 0px solid rgb(217, 217, 217); padding: 15px 15px 10px; min-height: 0px !important; flex: 0 0 33.3333%; color: rgb(34, 34, 34); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <div class="relatedContentCarousel__itemWrapper" style="box-sizing: inherit;">
                    <a class="relatedContentCarousel__imageLink" href="https://www.parents.com/health/autism/what-happened-to-aspergers/" style="box-sizing: inherit; background-color: transparent; color: rgb(0, 163, 185); text-decoration: none; display: block;">
                    <img class="relatedContentCarousel__image" src="https://images.parents.mdpcdn.com/sites/parents.com/files/styles/week_by_week_card/public/images/550_101789476.jpg" style="box-sizing: inherit; border: 0px; max-width: 100%; height: auto; display: inline-block; vertical-align: middle;" /></a><div class="relatedContentCarousel__metaWrapper" style="box-sizing: inherit; margin-top: 0.5rem;">
                        <span class="relatedContentCarousel__heading" style="box-sizing: inherit; font-size: 21px; line-height: 25px; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; max-height: 75px; overflow: hidden; text-overflow: ellipsis; text-align: center;"><a class="relatedContentCarousel__headingLink" href="https://www.parents.com/health/autism/what-happened-to-aspergers/" style="box-sizing: inherit; background-color: transparent; color: rgb(0, 0, 0); text-decoration: none; font-weight: 700;">What Happened to Asperger&#39;s?</a></span></div>
                </div>
            </div>
            <div class="relatedContentCarousel__item story" style="box-sizing: inherit; border: 0px solid rgb(217, 217, 217); padding: 15px 15px 10px; min-height: 0px !important; flex: 0 0 33.3333%; color: rgb(34, 34, 34); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <div class="relatedContentCarousel__itemWrapper" style="box-sizing: inherit;">
                    <a class="relatedContentCarousel__imageLink" href="https://www.parents.com/health/autism/symptoms/handling-your-childs-autism-diagnosis/" style="box-sizing: inherit; background-color: transparent; color: rgb(0, 163, 185); text-decoration: none; display: block;">
                    <img class="relatedContentCarousel__image" src="https://images.parents.mdpcdn.com/sites/parents.com/files/styles/week_by_week_card/public/images/p_101677662.jpg" style="box-sizing: inherit; border: 0px; max-width: 100%; height: auto; display: inline-block; vertical-align: middle;" /></a><div class="relatedContentCarousel__metaWrapper" style="box-sizing: inherit; margin-top: 0.5rem;">
                        <span class="relatedContentCarousel__heading" style="box-sizing: inherit; font-size: 21px; line-height: 25px; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; max-height: 75px; overflow: hidden; text-overflow: ellipsis; text-align: center;"><a class="relatedContentCarousel__headingLink" href="https://www.parents.com/health/autism/symptoms/handling-your-childs-autism-diagnosis/" style="box-sizing: inherit; background-color: transparent; color: rgb(0, 0, 0); text-decoration: none; font-weight: 700;">How to Handle Your Child&#39;s Autism Diagnosis</a></span></div>
                </div>
            </div>
            <div class="relatedContentCarousel__item story" style="box-sizing: inherit; border: 0px solid rgb(217, 217, 217); padding: 15px 15px 10px; min-height: 0px !important; flex: 0 0 33.3333%; color: rgb(34, 34, 34); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <div class="relatedContentCarousel__itemWrapper" style="box-sizing: inherit;">
                    <a class="relatedContentCarousel__imageLink" href="https://www.parents.com/health/autism/facts/types-of-autism/" style="box-sizing: inherit; background-color: transparent; color: rgb(0, 163, 185); text-decoration: none; display: block; cursor: pointer; opacity: 0.7;">
                    <img class="relatedContentCarousel__image" src="https://images.parents.mdpcdn.com/sites/parents.com/files/styles/week_by_week_card/public/nito.jpg" style="box-sizing: inherit; border: 0px; max-width: 100%; height: auto; display: inline-block; vertical-align: middle;" /></a><div class="relatedContentCarousel__metaWrapper" style="box-sizing: inherit; margin-top: 0.5rem;">
                        <span class="relatedContentCarousel__heading" style="box-sizing: inherit; font-size: 21px; line-height: 25px; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; max-height: 75px; overflow: hidden; text-overflow: ellipsis; text-align: center;"><a class="relatedContentCarousel__headingLink" href="https://www.parents.com/health/autism/facts/types-of-autism/" style="box-sizing: inherit; background-color: transparent; color: rgb(0, 0, 0); text-decoration: none; font-weight: 700;">The New Look of Autism</a></span></div>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td>&nbsp;</td>
    </tr>
</table>
</asp:Content>

