<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="news.aspx.cs" Inherits="news" %>

<asp:Content ID="Content1" ContentPlaceHolderID="title" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            height: 22px;
        }
        .auto-style3 {
            height: 90px;
        }
        .auto-style4 {
            font-size: xx-large;
            color: #660033;
        }
    </style>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Contentbody" Runat="Server">
    <table class="auto-style1">
        <tr>
            <td colspan="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span class="auto-style4"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Events&nbsp;</strong></span></td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style3">
                <img alt="Image result for events of an autism school" src="http://cinema.usc.edu/userfiles/5DA63C519FF6844528DF3BC4E89ED474DB19F94Eimages/4x6%20Front%20Online(1).png" style="height: 338px; width: 362px; margin-top: 0px" /></td>
            <td class="auto-style3">
                <img alt="Image result for events of an autism school" src="https://i.pinimg.com/736x/d2/a6/7f/d2a67fc158d04efdbceca83c95ea040a--register-online-the-fun.jpg" style="height: 339px; width: 385px" /></td>
            <td class="auto-style3"></td>
        </tr>
        <tr>
            <td class="auto-style2" colspan="2">
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Autism Awareness Wristbands:&nbsp;<span>&nbsp;</span></strong>Sell Autism Speaks wristbands for $1-$3 each in the cafeteria, at sports games, in coffee shops, before/after class, etc.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Bake Sales:</strong><span>&nbsp;</span>Hold a bake sale and decorate items with blue frosting and puzzle pieces. Order an Autism Speaks puzzle piece cookie cutter.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Celebrate Your Birthday:</strong><span>&nbsp;</span>This year, consider donating your birthday to help those with autism. Throw a party or celebrate the way you normally would, but let all your friends and family you are dedicating your birthday to Autism Speaks. Set up a fundraising page&nbsp;and direct friends to the link so they can donate in honor of your birthday.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Dance Marathon:</strong><span>&nbsp;</span>Dance the night away and raise funds and autism awareness. Ask your school to donate event space and have student musicians and DJs donate their time and talent.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Email Campaign:</strong><span>&nbsp;</span>Email friends and family and ask them to donate to your Autism Speaks fundraising page.
                </p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Fashion Show:</strong><span>&nbsp;</span>Work with a local stores to put on a fashion show using student models! Ask a DJ to volunteer their time and talent, secure a donated space and sell tickets!</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Garage Sale:</strong><span>&nbsp;</span>Organize a school garage/tag sale. Sell old clothes, movies, CDs, electronics, etc.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Homecoming Treats</strong>: Set up a table at your school’s homecoming event.&nbsp; Sell blue treats like snow cones, sports drink, cotton candy, etc.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Informational Speakers</strong>: Host a panel discussion to raise autism awareness. Speakers can include individuals on the spectrum, family members of individuals with autism or professionals in the field. Reach out to your local<span>&nbsp;</span><a href="https://www.autismspeaks.org/about-us/contact-us" style="color: rgb(40, 65, 119); text-decoration: underline;" target="_blank">Autism Speaks contact</a><span>&nbsp;</span>to find out about getting an informational speaker to come to your school.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Just Wear Blue Day:</strong><span>&nbsp;</span>Ask classmates, friends and teachers to wear blue to raise autism awareness. This is a great way to<span>&nbsp;</span><em>Light It Up Blue</em><span>&nbsp;</span>during Autism Awareness Month! Snap a picture, post it on Facebook, Twitter or Instagram and be sure to use #autismspeaksclub and #LIUB!</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;"></strong><span>&nbsp;</span><a href="#" style="color: rgb(40, 65, 119); text-decoration: underline;" target="_blank">fundraising campaign kit</a><span>&nbsp;</span><span>&nbsp;</span><a href="#" style="color: rgb(40, 65, 119); text-decoration: underline;" target="_blank">here</a><span>&nbsp;</span>to get your Kids and Coins Toolkit.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Luncheon or Pancake Breakfast:<span>&nbsp;</span></strong>Sell tickets to a special luncheon or pancake breakfast.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Movie Night</strong>: Show a movie about autism! You can charge admission and/or sell tickets, popcorn, ice cream, candy, blue cupcakes/cookies, etc.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Night at the Bowling Alley:<span>&nbsp;</span></strong>Contact a local bowling alley to see if they will donate the lanes for a night and host a bowling tournament. Have attendees form teams, sell refreshments and donate the proceeds to Autism Speaks. See if they can light the lanes blue too!</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Puzzle Piece Campaign</strong>: Sell Autism Speaks puzzle piece cards for $1, $5, or $10 each at your school and in the local community. Hang them up in school to help raise awareness.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Quiz Bowl</strong>: Similar to a trivia night, this event can be hosted at school, coffee shop or restaurant. Get prizes donated to entice students to come out and test their trivia knowledge!</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Restaurant Week</strong>: Call local restaurants and ask if they will participate in a fundraising night in which a percentage of proceeds are donated to Autism Speaks.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Scavenger Hunt:</strong><span>&nbsp;</span>Recruit students, sports teams, clubs and even teachers to participate in a fun scavenger hunt. Sell tickets, get prizes donated and ask everyone to wear blue to raise autism awareness.</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Team Sports Awareness Night</strong>: Partner with one of your school’s sports teams and have them dedicate a game to raising autism awareness. Players can even wear blue shoelaces or socks! Donate a percentage of ticket sales, set up change buckets, and/or sell t-shirts as a fundraiser!</p>
                <p style="margin: 1em auto; text-align: left !important; color: rgb(1, 1, 1); font-family: &quot;Open Sans&quot;, Arial, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="font-weight: bold;">Ultimate Frisbee Tournament</strong>: Host an ultimate frisbee tournament at your school or a local park. Have students form teams and pay an entry fee. Add an incentive by getting prizes donated from sponsors.</p>
            </td>
            <td class="auto-style2">&nbsp;</td>
        </tr>
    </table>
</asp:Content>

