<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="plan.aspx.cs" Inherits="plan" %>

<asp:Content ID="Content1" ContentPlaceHolderID="title" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
    </style>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Contentbody" Runat="Server">
    <table class="auto-style1">
        <tr>
            <td>
                <img alt="Autism Quote 7" src="http://blog.autismtreatmentcenter.org/wp-content/uploads/2016/08/AutismQuote7.jpg" style="height: 714px; width: 1492px" /></td>
        </tr>
        <tr>
            <td>
                <p style="box-sizing: border-box; margin-top: 0px; margin-right: 0px; margin-bottom: 15px !important; margin-left: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: medium; line-height: 1.4 !important; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; color: rgb(51, 51, 51); list-style: initial !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Educational planning for students with autism often addresses a wide range of skill development, including academics, communication and language, social skills, self-help skills, behavioral issues, self-advocacy and leisure-related skills. It’s important to consult with professionals trained specifically in autism to help a child benefit from his/her school program. Obtaining a&nbsp;<a href="https://www.autism-society.org/about-the-autism-society/guiding-principles/options-policy/" style="box-sizing: border-box; background: linear-gradient(rgb(181, 181, 181), rgb(181, 181, 181)) 0% 95% / 1px 1px repeat-x transparent; color: rgb(43, 86, 160); text-decoration: none; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; transition: all 0.25s ease-out; text-shadow: rgb(255, 255, 255) 0.03em 0px, rgb(255, 255, 255) -0.03em 0px, rgb(255, 255, 255) 0px 0.03em, rgb(255, 255, 255) 0px -0.03em, rgb(255, 255, 255) 0.06em 0px, rgb(255, 255, 255) -0.06em 0px, rgb(255, 255, 255) 0.09em 0px, rgb(255, 255, 255) -0.09em 0px, rgb(255, 255, 255) 0.12em 0px, rgb(255, 255, 255) -0.12em 0px, rgb(255, 255, 255) 0.15em 0px, rgb(255, 255, 255) -0.15em 0px;">range 
                    of opinions</a>&nbsp;is also useful.</p>
                <p style="box-sizing: border-box; margin-top: 0px; margin-right: 0px; margin-bottom: 15px !important; margin-left: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: medium; line-height: 1.4 !important; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; color: rgb(51, 51, 51); list-style: initial !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Most professionals agree that school-age children with autism respond well to highly structured, specialized education programs designed to meet individual needs. Based on the major characteristics associated with autism, it is important to consider:</p>
                <ul style="box-sizing: border-box; margin: 0.5em 0px 0.5em 35px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: medium; line-height: inherit; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; list-style: initial !important; color: rgb(51, 51, 51); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <li style="box-sizing: border-box; margin-top: 0px; margin-right: 0px; margin-bottom: 15px !important; margin-left: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.4 !important; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; list-style: initial !important;">Social skill development</li>
                    <li style="box-sizing: border-box; margin-top: 0px; margin-right: 0px; margin-bottom: 15px !important; margin-left: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.4 !important; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; list-style: initial !important;">Communication</li>
                    <li style="box-sizing: border-box; margin-top: 0px; margin-right: 0px; margin-bottom: 15px !important; margin-left: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.4 !important; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; list-style: initial !important;">Behavior</li>
                    <li style="box-sizing: border-box; margin-top: 0px; margin-right: 0px; margin-bottom: 15px !important; margin-left: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.4 !important; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; list-style: initial !important;">Sensory integration</li>
                </ul>
                <p style="box-sizing: border-box; margin-top: 0px; margin-right: 0px; margin-bottom: 15px !important; margin-left: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: medium; line-height: 1.4 !important; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; color: rgb(51, 51, 51); list-style: initial !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Programs sometimes include several treatment components coordinated to assist a person with autism. For example, one child’s plan may consist of speech therapy, social skill development and medication, all within a structured behavior program. Another student may be working on social skill development, sensory integration and dietary changes.<span>&nbsp;</span><strong style="box-sizing: border-box; font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline;">No one program or diet is perfect for every person with autism</strong>; it’s important to try several approaches and find the ones that work best. As the&nbsp;<a href="https://www.autism-society.org/about-the-autism-society/guiding-principles/options-policy/" style="box-sizing: border-box; background: linear-gradient(rgb(181, 181, 181), rgb(181, 181, 181)) 0% 95% / 1px 1px repeat-x transparent; color: rgb(43, 86, 160); text-decoration: none; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; transition: all 0.25s ease-out; text-shadow: rgb(255, 255, 255) 0.03em 0px, rgb(255, 255, 255) -0.03em 0px, rgb(255, 255, 255) 0px 0.03em, rgb(255, 255, 255) 0px -0.03em, rgb(255, 255, 255) 0.06em 0px, rgb(255, 255, 255) -0.06em 0px, rgb(255, 255, 255) 0.09em 0px, rgb(255, 255, 255) -0.09em 0px, rgb(255, 255, 255) 0.12em 0px, rgb(255, 255, 255) -0.12em 0px, rgb(255, 255, 255) 0.15em 0px, rgb(255, 255, 255) -0.15em 0px;">Autism 
                    Society’s Options Policy</a>&nbsp;states<strong style="box-sizing: border-box; font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline;">: “Each family and individual with autism should have the right to learn about and then select the options that they feel are most appropriate for the individual with autism.”</strong></p>
                <p style="box-sizing: border-box; margin-top: 0px; margin-right: 0px; margin-bottom: 15px !important; margin-left: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: medium; line-height: 1.4 !important; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; color: rgb(51, 51, 51); list-style: initial !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <a href="http://www.abilitypath.org/" rel="noopener" style="box-sizing: border-box; background: linear-gradient(rgb(181, 181, 181), rgb(181, 181, 181)) 0% 95% / 1px 1px repeat-x transparent; color: rgb(43, 86, 160); text-decoration: none; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; transition: all 0.25s ease-out; text-shadow: rgb(255, 255, 255) 0.03em 0px, rgb(255, 255, 255) -0.03em 0px, rgb(255, 255, 255) 0px 0.03em, rgb(255, 255, 255) 0px -0.03em, rgb(255, 255, 255) 0.06em 0px, rgb(255, 255, 255) -0.06em 0px, rgb(255, 255, 255) 0.09em 0px, rgb(255, 255, 255) -0.09em 0px, rgb(255, 255, 255) 0.12em 0px, rgb(255, 255, 255) -0.12em 0px, rgb(255, 255, 255) 0.15em 0px, rgb(255, 255, 255) -0.15em 0px;" target="_blank">
                    AbilityPath.org</a>’s<span>&nbsp;</span><a href="http://abilitypath.org/wp-content/uploads/2015/12/life-after-high-school.pdf" rel="noopener" style="box-sizing: border-box; background: linear-gradient(rgb(181, 181, 181), rgb(181, 181, 181)) 0% 95% / 1px 1px repeat-x transparent; color: rgb(43, 86, 160); text-decoration: none; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; transition: all 0.25s ease-out; text-shadow: rgb(255, 255, 255) 0.03em 0px, rgb(255, 255, 255) -0.03em 0px, rgb(255, 255, 255) 0px 0.03em, rgb(255, 255, 255) 0px -0.03em, rgb(255, 255, 255) 0.06em 0px, rgb(255, 255, 255) -0.06em 0px, rgb(255, 255, 255) 0.09em 0px, rgb(255, 255, 255) -0.09em 0px, rgb(255, 255, 255) 0.12em 0px, rgb(255, 255, 255) -0.12em 0px, rgb(255, 255, 255) 0.15em 0px, rgb(255, 255, 255) -0.15em 0px;" target="_blank">road 
                    map for success after high school</a><span>&nbsp;</span>contains great information and advice for parents of students with special needs. As this document mentions,<span>&nbsp;</span><strong style="box-sizing: border-box; font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline;">the person with autism must be involved in planning his/her future.</strong><span>&nbsp;</span>Person-centered planning – explaining the planning process to your child, asking him/her for input and teaching<span>&nbsp;</span><a href="https://www.autism-society.org/living-with-autism/autism-through-the-lifespan/self-advocacy/" style="box-sizing: border-box; background: linear-gradient(rgb(181, 181, 181), rgb(181, 181, 181)) 0% 95% / 1px 1px repeat-x transparent; color: rgb(43, 86, 160); text-decoration: none; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; transition: all 0.25s ease-out; text-shadow: rgb(255, 255, 255) 0.03em 0px, rgb(255, 255, 255) -0.03em 0px, rgb(255, 255, 255) 0px 0.03em, rgb(255, 255, 255) 0px -0.03em, rgb(255, 255, 255) 0.06em 0px, rgb(255, 255, 255) -0.06em 0px, rgb(255, 255, 255) 0.09em 0px, rgb(255, 255, 255) -0.09em 0px, rgb(255, 255, 255) 0.12em 0px, rgb(255, 255, 255) -0.12em 0px, rgb(255, 255, 255) 0.15em 0px, rgb(255, 255, 255) -0.15em 0px;">self-advocacy 
                    skills</a><span>&nbsp;</span>– is incredibly important&nbsp;in creating the best educational plan<span>&nbsp;</span><em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: italic; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline;">and</em>&nbsp;in fostering good communication, executive functioning skills and independence.</p>
                <p style="box-sizing: border-box; margin-top: 0px; margin-right: 0px; margin-bottom: 15px !important; margin-left: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: medium; line-height: 1.4 !important; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; color: rgb(51, 51, 51); list-style: initial !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="box-sizing: border-box; font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline;">Parents and professionals need to work together.</strong><span>&nbsp;</span>Teachers should have some understanding of the child’s behavior and communication skills at home, and parents should let educators know about their expectations, as well as which techniques work at home. Open communication between school staff and parents can lead to better goal-setting and evaluation of a student’s progress.</p>
                <p style="box-sizing: border-box; margin-top: 0px; margin-right: 0px; margin-bottom: 15px !important; margin-left: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: medium; line-height: 1.4 !important; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; color: rgb(51, 51, 51); list-style: initial !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="box-sizing: border-box; font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline;">Community goals</strong>, such as purchasing meals and grocery shopping, can be reinforced through job assignments in the classroom;<span>&nbsp;</span><strong style="box-sizing: border-box; font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline;">leisure goals</strong>, such as taking time to engage in a hobby each 
                    day, can also be practiced at school.</p>
                <p style="box-sizing: border-box; margin-top: 0px; margin-right: 0px; margin-bottom: 15px !important; margin-left: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: medium; line-height: 1.4 !important; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; color: rgb(51, 51, 51); list-style: initial !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <strong style="box-sizing: border-box; font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline;">Academic goals need to be tailored to the student’s intellectual ability and functioning level.</strong><span>&nbsp;</span>Some children need help understanding social situations and developing appropriate responses. Others exhibit aggressive or self-injurious behavior, and need assistance managing their behaviors. No one program will meet the needs of all individuals with the disability, so it is important to find the program or programs that best fit your child’s needs.<span>&nbsp;</span><strong style="box-sizing: border-box; font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline;">Just 
                    like&nbsp;<a href="https://www.autism-society.org/living-with-autism/preview!www.autism-society.org/living-with-autism/treatment-options/" style="box-sizing: border-box; background: linear-gradient(rgb(181, 181, 181), rgb(181, 181, 181)) 0% 95% / 1px 1px repeat-x transparent; color: rgb(43, 86, 160); text-decoration: none; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: roboto, &quot;Open Sans&quot;, open-sans, Helvetica, Arial, sans-serif; text-rendering: geometricPrecision; -webkit-font-smoothing: antialiased; vertical-align: baseline; transition: all 0.25s ease-out; text-shadow: rgb(255, 255, 255) 0.03em 0px, rgb(255, 255, 255) -0.03em 0px, rgb(255, 255, 255) 0px 0.03em, rgb(255, 255, 255) 0px -0.03em, rgb(255, 255, 255) 0.06em 0px, rgb(255, 255, 255) -0.06em 0px, rgb(255, 255, 255) 0.09em 0px, rgb(255, 255, 255) -0.09em 0px, rgb(255, 255, 255) 0.12em 0px, rgb(255, 255, 255) -0.12em 0px, rgb(255, 255, 255) 0.15em 0px, rgb(255, 255, 255) -0.15em 0px;">treatment 
                    approaches</a>, educational programs should be tailored to the child’s individual needs, flexible and re-evaluated on a regular basis.</strong></p>
            </td>
        </tr>
    </table>
</asp:Content>

