<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="service.aspx.cs" Inherits="service" %>

<asp:Content ID="Content1" ContentPlaceHolderID="title" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Contentbody" Runat="Server">
    <div class="jumbotron" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; padding: 19px; margin-bottom: 20px; color: rgb(51, 51, 51); background-color: rgb(255, 255, 255); flex-direction: column; border-radius: 2px; box-shadow: none; border: 0px; font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <h1 style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 2rem 0px 10px; font-weight: 300; font-family: &quot;Libre Franklin&quot;, Helvetica, Arial, sans-serif; font-size: 2.5rem; color: rgb(0, 100, 178); line-height: 3rem; padding-bottom: 9px; border-bottom: 1px solid rgb(100, 160, 200);">School services for autism spectrum disorder (ASD)</h1>
        <a class="author" href="https://www.aboutkidshealth.ca/Contributors#Neurology" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; color: rgb(55, 63, 71); text-decoration: none; background-color: transparent; border-bottom: 1px solid rgb(0, 100, 178); max-width: 300px; word-break: break-word; font-weight: 700; font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif; font-size: 1rem; display: block;">By SickKids hospital staff</a></div>
    <div id="article-overview" class="panel-body" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; padding: 0px 0px 8px; clear: both; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        <p style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1rem 0px 0.9rem; color: rgb(0, 100, 178); line-height: 1.8rem; word-break: break-word; font-weight: 400; font-size: 1.2rem;">
            Provides information about the various services that are available in schools for children with autism spectrum disorder. Also provides information about other programs that can be used to help pre-school and school-age children.<br style="box-sizing: border-box; -webkit-tap-highlight-color: transparent;" />
        </p>
    </div>
    <div class="panel" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin-bottom: 1rem; background-color: rgb(255, 255, 255); border: 0px; border-radius: 2px; box-shadow: none; clear: both; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <div class="panel-body" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; padding: 0px;">
        </div>
    </div>
    <div class="panel" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin-bottom: 1rem; background-color: rgb(255, 255, 255); border: 0px; border-radius: 2px; box-shadow: none; clear: both; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <div class="panel-body" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; padding: 0px;">
            <h2 style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1.5rem auto 1rem; font-weight: 300; font-family: &quot;Libre Franklin&quot;, Helvetica, Arial, sans-serif; color: rgb(0, 100, 178); font-size: 2rem; line-height: 2.5rem;">Pre-School Services</h2>
            <h3 style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 20px auto 10px; font-weight: 800; font-family: &quot;Libre Franklin&quot;, Helvetica, Arial, sans-serif; color: rgb(55, 63, 71); font-size: 1.4rem; line-height: 1.1;">The City of Toronto&#39;s Children, Youth &amp; Parenting Division<br style="box-sizing: border-box; -webkit-tap-highlight-color: transparent;" />
            </h3>
            <p style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1rem 0px 0.9rem; color: rgb(55, 63, 71); line-height: 1.5rem; word-break: break-word;">
                Toronto Children, Youth &amp; Parenting provides families of children from birth to nine years of age with detailed information on licensed child care options in Toronto. These include child care centres, specialized nursery programs,<span style="box-sizing: border-box; -webkit-tap-highlight-color: transparent">&nbsp;</span>and home care arranged through a licensed private home agency. It also provides assistance in placement and care of children with special needs, and a registry of family resource and parent programs. They also administer the child care fee subsidy program for families who need help paying for licensed child care.</p>
            <p style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1rem 0px 0.9rem; color: rgb(55, 63, 71); line-height: 1.5rem; word-break: break-word;">
                If you are a parent, foster parent, or legal guardian, you may qualify for money to help pay for all or part of your child care. It will depend on your income and job. Toronto Children, Youth &amp; Parenting is committed to the inclusion of children with special needs.</p>
            <p style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1rem 0px 0.9rem; color: rgb(55, 63, 71); line-height: 1.5rem; word-break: break-word;">
                For more information, visit<span>&nbsp;</span><a href="https://www.toronto.ca/community-people/children-parenting/" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; color: rgb(55, 63, 71); text-decoration: none; background-color: transparent; border-bottom: 1px solid rgb(0, 175, 216); max-width: 300px; word-break: break-word;">www.toronto.ca/community-people/children-parenting</a>.<br style="box-sizing: border-box; -webkit-tap-highlight-color: transparent;" />
            </p>
            <h3 style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 20px auto 10px; font-weight: 800; font-family: &quot;Libre Franklin&quot;, Helvetica, Arial, sans-serif; color: rgb(55, 63, 71); font-size: 1.4rem; line-height: 1.1;">EarlyON centres</h3>
            <p style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1rem 0px 0.9rem; color: rgb(55, 63, 71); line-height: 1.5rem; word-break: break-word;">
                EarlyON centres are places where parents and caregivers of children from birth to six years of age can:</p>
            <ul style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin-top: 0px; margin-bottom: 10px;">
                <li style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; line-height: 1.5rem; margin-bottom: 0.5rem; font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif;">take part with their children in a range of programs and activities</li>
                <li style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; line-height: 1.5rem; margin-bottom: 0.5rem; font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif;">get answers to questions about child development</li>
                <li style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; line-height: 1.5rem; margin-bottom: 0.5rem; font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif;">get information about programs and services that are available for young children and their families</li>
                <li style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; line-height: 1.5rem; margin-bottom: 0.5rem; font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif;">talk to early years professionals, as well as other parents and caregivers in the community.</li>
            </ul>
            <p style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1rem 0px 0.9rem; color: rgb(55, 63, 71); line-height: 1.5rem; word-break: break-word;">
                To find a centre closest to you, visit<span>&nbsp;</span><a href="https://www.ontario.ca/page/find-earlyon-child-and-family-centre" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; color: rgb(55, 63, 71); text-decoration: none; background-color: transparent; border-bottom: 1px solid rgb(0, 175, 216); max-width: 300px; word-break: break-word;">www.ontario.ca</a>.</p>
            <h3 style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 20px auto 10px; font-weight: 800; font-family: &quot;Libre Franklin&quot;, Helvetica, Arial, sans-serif; color: rgb(55, 63, 71); font-size: 1.4rem; line-height: 1.1;">Parenting and Family Literacy Centres</h3>
            <p style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1rem 0px 0.9rem; color: rgb(55, 63, 71); line-height: 1.5rem; word-break: break-word;">
                Parenting and Family Literacy Centres are free school-based programs for parents, grandparents, and caregivers with children up to six years of age. They are administered by the Toronto District School Board.</p>
            <p style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1rem 0px 0.9rem; color: rgb(55, 63, 71); line-height: 1.5rem; word-break: break-word;">
                These centres offer a fun, play-based program to support children’s early learning and development. They provide a place for parents to learn and connect with each other. The centres provide opportunities for parents and children to:</p>
            <ul style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin-top: 0px; margin-bottom: 10px;">
                <li style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; line-height: 1.5rem; margin-bottom: 0.5rem; font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif;">become familiar with their school</li>
                <li style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; line-height: 1.5rem; margin-bottom: 0.5rem; font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif;">establish positive home-school connections</li>
                <li style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; line-height: 1.5rem; margin-bottom: 0.5rem; font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif;">participate in a family literacy program that helps children develop and build essential literacy and numeracy skills</li>
                <li style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; line-height: 1.5rem; margin-bottom: 0.5rem; font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif;">get information about community resources</li>
                <li style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; line-height: 1.5rem; margin-bottom: 0.5rem; font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif;">discuss parenting concerns and seek referrals if necessary</li>
                <li style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; line-height: 1.5rem; margin-bottom: 0.5rem; font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif;">borrow multilingual books</li>
            </ul>
            <p style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1rem 0px 0.9rem; color: rgb(55, 63, 71); line-height: 1.5rem; word-break: break-word;">
                For more information, visit:<span>&nbsp;</span><a href="http://www.tdsb.on.ca/_site/ViewItem.asp?siteid=201&amp;menuid=1001&amp;pageid=732" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; color: rgb(55, 63, 71); text-decoration: none; background-color: transparent; border-bottom: 1px solid rgb(0, 175, 216); max-width: 300px; word-break: break-word;">www.tdsb.on.ca</a>.<br style="box-sizing: border-box; -webkit-tap-highlight-color: transparent;" />
            </p>
            <h2 style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1.5rem auto 1rem; font-weight: 300; font-family: &quot;Libre Franklin&quot;, Helvetica, Arial, sans-serif; color: rgb(0, 100, 178); font-size: 2rem; line-height: 2.5rem;">School-age services</h2>
            <p style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1rem 0px 0.9rem; color: rgb(55, 63, 71); line-height: 1.5rem; word-break: break-word;">
                Most school boards have ASD support personnel who will consult with your child’s teacher. Referrals are made by the teacher or principal of the school. Ask your teacher or principal what support your school can offer to students diagnosed with ASD. School boards will require a diagnosis in the child’s Ontario School Record (OSR) and your signature will be needed on the referral form.</p>
            <h3 style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 20px auto 10px; font-weight: 800; font-family: &quot;Libre Franklin&quot;, Helvetica, Arial, sans-serif; color: rgb(55, 63, 71); font-size: 1.4rem; line-height: 1.1;">Ministry of Education</h3>
            <p style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1rem 0px 0.9rem; color: rgb(55, 63, 71); line-height: 1.5rem; word-break: break-word;">
                The Ontario Ministry of Education provides information regarding your child&#39;s future education which includes:</p>
            <ul style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin-top: 0px; margin-bottom: 10px;">
                <li style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; line-height: 1.5rem; margin-bottom: 0.5rem; font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif;">information about their individual education plan (IEP) if they have one</li>
                <li style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; line-height: 1.5rem; margin-bottom: 0.5rem; font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif;">the transitions which may occur whether they are entering the school system for the first time or they change to a new classroom or grade</li>
                <li style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; line-height: 1.5rem; margin-bottom: 0.5rem; font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif;">the difference between Applied Behavioural Analysis (ABA) and Intensive Behavioural Intervention (IBI)</li>
                <li style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; line-height: 1.5rem; margin-bottom: 0.5rem; font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif;">who to contact if you have questions about your child&#39;s education or services and supports for your child</li>
            </ul>
            <p style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1rem 0px 0.9rem; color: rgb(55, 63, 71); line-height: 1.5rem; word-break: break-word;">
                For more information, visit<span>&nbsp;</span><a href="http://www.edu.gov.on.ca/" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; color: rgb(55, 63, 71); text-decoration: none; background-color: transparent; border-bottom: 1px solid rgb(0, 175, 216); max-width: 300px; word-break: break-word;">www.edu.gov.on.ca</a>.</p>
            <h3 style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 20px auto 10px; font-weight: 800; font-family: &quot;Libre Franklin&quot;, Helvetica, Arial, sans-serif; color: rgb(55, 63, 71); font-size: 1.4rem; line-height: 1.1;">Toronto District School Board (TDSB) and Toronto Catholic District School Board (TCDSB)</h3>
            <p style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1rem 0px 0.9rem; color: rgb(55, 63, 71); line-height: 1.5rem; word-break: break-word;">
                Both the Toronto District School Board and Toronto Catholic District School Board offer a variety of special education services and programming for children with special needs.</p>
            <p style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1rem 0px 0.9rem; color: rgb(55, 63, 71); line-height: 1.5rem; word-break: break-word;">
                Information about these services can be found at the following websites:<span>&nbsp;</span><a href="http://www.tdsb.on.ca/" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; color: rgb(55, 63, 71); text-decoration: none; background-color: transparent; border-bottom: 1px solid rgb(0, 175, 216); max-width: 300px; word-break: break-word;">www.tdsb.on.ca<span>&nbsp;</span></a>(TDSB) and<a href="http://www.tcdsb.org/" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; color: rgb(55, 63, 71); text-decoration: none; background-color: transparent; border-bottom: 1px solid rgb(0, 175, 216); max-width: 300px; word-break: break-word;">www.tcdsb.org<span>&nbsp;</span></a>(TCDSB).</p>
            <p style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1rem 0px 0.9rem; color: rgb(55, 63, 71); line-height: 1.5rem; word-break: break-word;">
                Information about the Special Education Advisory Committee (SEAC) can also be found on the school board websites. SEACs make recommendations to school boards regarding the development and delivery of special education programs and services for students with special needs, also known as “exceptional students.” They take part in the school board’s annual review of its special education plan and review the budget and financial statements. SEACs also provide important information to parents.</p>
            <h3 style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 20px auto 10px; font-weight: 800; font-family: &quot;Libre Franklin&quot;, Helvetica, Arial, sans-serif; color: rgb(55, 63, 71); font-size: 1.4rem; line-height: 1.1;">People for Education</h3>
            <p style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1rem 0px 0.9rem; color: rgb(55, 63, 71); line-height: 1.5rem; word-break: break-word;">
                People for Education is an independent parent-led organization, working to improve public education in Ontario&#39;s English, Catholic, and French schools. Their website provides very useful information to parents written in 15 languages.</p>
            <p style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 1rem 0px 0.9rem; color: rgb(55, 63, 71); line-height: 1.5rem; word-break: break-word;">
                For more information, visit<span>&nbsp;</span><a href="http://www.peopleforeducation.ca/" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; color: rgb(55, 63, 71); text-decoration: none; background-color: transparent; border-bottom: 1px solid rgb(0, 175, 216); max-width: 300px; word-break: break-word;">www.peopleforeducation.ca</a>.</p>
        </div>
    </div>
    <small id="review-date" class="pull-left" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; font-size: 0.875rem; float: left !important; font-family: &quot;Open Sans&quot;, Helvetica, Arial, sans-serif; color: rgb(136, 145, 152); clear: right; width: 760px; margin: 15px 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Last updated: March 9th 2009</small>
</asp:Content>

