<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="therapy.aspx.cs" Inherits="therapy" %>

<asp:Content ID="Content1" ContentPlaceHolderID="title" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
    </style>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Contentbody" Runat="Server">
    <table class="auto-style1">
        <tr>
            <td>
                <img alt="Image result for outdoor activities for autism teachers" src="http://www.ourkids.net/images/pp/kinark-2018-autism-camp.jpg" opacity:0.5px style="width: 1468px" /></td>
        </tr>
        <tr>
            <td>
                <span style="color: rgb(204, 51, 255); font-family: &quot;Open Sans&quot;, sans-serif; font-size: x-large; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 700; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">“It takes a village to raise a child. It takes a child with autism to raise the consciousness of the village.” – Coach Elaine Hall</span></td>
        </tr>
        <tr>
            <td>
                <div class="row" data-aos="fade-up" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin-left: -15px; margin-right: -15px; text-align: center; color: rgb(60, 72, 88); font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <article class="col-xs-12 col-ms-10 col-ms-offset-1 col-sm-8 col-sm-offset-2 col-md-4 hestia-blog-item" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; display: inline-block; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float: none !important; width: 390px; margin-left: -4px; text-align: left; margin-right: -4px; vertical-align: top;">
                        <div class="card card-plain card-blog" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; display: inline-block; position: relative; width: 360px; margin-bottom: 30px; border-radius: 6px; color: rgba(0, 0, 0, 0.87); background: transparent; box-shadow: none; margin-top: 30px;">
                            <div class="card-image" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; overflow: hidden; position: relative; height: 240px; margin: 0px; border-radius: 3px; transition: all 300ms cubic-bezier(0.34, 1.61, 0.7, 1); transform: translate(0px, 0px); box-shadow: rgba(0, 0, 0, 0.56) 0px 16px 38px -12px, rgba(0, 0, 0, 0.12) 0px 4px 25px 0px, rgba(0, 0, 0, 0.2) 0px 8px 10px -5px;">
                                <a href="#" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; background-color: transparent; color: rgb(105, 80, 162); text-decoration: none; transition: 0.3s ease; display: block;" title="GUEST POST: Top 5 Educational Apps for Children with Autism">
                                <img alt="" class="attachment-hestia-blog size-hestia-blog wp-post-image" height="240" sizes="(max-width: 360px) 100vw, 360px" src="https://i1.wp.com/asdteacher.com/wp-content/uploads/2018/05/educational-apps-for-children-with-autism.jpeg?resize=360%2C240" srcset="https://i1.wp.com/asdteacher.com/wp-content/uploads/2018/05/educational-apps-for-children-with-autism.jpeg?w=1880 1880w, https://i1.wp.com/asdteacher.com/wp-content/uploads/2018/05/educational-apps-for-children-with-autism.jpeg?resize=300%2C200 300w, https://i1.wp.com/asdteacher.com/wp-content/uploads/2018/05/educational-apps-for-children-with-autism.jpeg?resize=768%2C512 768w, https://i1.wp.com/asdteacher.com/wp-content/uploads/2018/05/educational-apps-for-children-with-autism.jpeg?resize=1024%2C682 1024w, https://i1.wp.com/asdteacher.com/wp-content/uploads/2018/05/educational-apps-for-children-with-autism.jpeg?resize=360%2C240 360w, https://i1.wp.com/asdteacher.com/wp-content/uploads/2018/05/educational-apps-for-children-with-autism.jpeg?resize=600%2C400 600w, https://i1.wp.com/asdteacher.com/wp-content/uploads/2018/05/educational-apps-for-children-with-autism.jpeg?w=1500 1500w" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; border: 0px; vertical-align: middle; max-width: 100%; height: 240px; width: 360px; border-radius: 3px; margin: 0px !important; transition: 1s ease-out;" width="360" /></a></div>
                            <div class="content" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; padding: 15px 5px;">
                                <h6 class="category" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.618; color: rgb(153, 153, 153); margin-top: 10px; margin-bottom: 10px; font-size: 12px; text-transform: uppercase;">&nbsp;</h6>
                                <h4 class="card-title" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; font-family: &quot;Roboto Slab&quot;, &quot;Times New Roman&quot;, serif; font-weight: 700; line-height: 1.4; color: rgb(60, 72, 88); margin-top: 5px; margin-bottom: 10px; font-size: 18px; text-decoration: none; word-wrap: break-word;"><a class="blog-item-title-link" href="http://asdteacher.com/guest-post-top-5-educational-apps-for-children-with-autism/" rel="bookmark" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; background-color: transparent; color: rgb(60, 72, 88); text-decoration: none; transition: 0.3s ease; word-wrap: break-word;" title="GUEST POST: Top 5 Educational Apps for Children with Autism">GUEST POST: Top 5 Educational Apps for Children with Autism</a></h4>
                                <p class="card-description" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 0px 0px 10px; font-size: 14px; color: rgb(153, 153, 153);">
                                    Written by&nbsp;Jamie Barnes Recent data shows that approximately 1% of the world’s population are on the autism spectrum. This is a twenty-fold increase from studies conducted more than two decades ago, though the rise in autistic children was high.</p>
                            </div>
                        </div>
                    </article>
                    <span>&nbsp;</span><article class="col-xs-12 col-ms-10 col-ms-offset-1 col-sm-8 col-sm-offset-2 col-md-4 hestia-blog-item" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; display: inline-block; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float: none !important; width: 390px; margin-left: -4px; text-align: left; margin-right: -4px; vertical-align: top;">
                        <div class="card card-plain card-blog" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; display: inline-block; position: relative; width: 360px; margin-bottom: 30px; border-radius: 6px; color: rgba(0, 0, 0, 0.87); background: transparent; box-shadow: none; margin-top: 30px;">
                            <div class="card-image" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; overflow: hidden; position: relative; height: 240px; margin: 0px; border-radius: 3px; transition: all 300ms cubic-bezier(0.34, 1.61, 0.7, 1); transform: translate(0px, 0px); box-shadow: rgba(0, 0, 0, 0.56) 0px 16px 38px -12px, rgba(0, 0, 0, 0.12) 0px 4px 25px 0px, rgba(0, 0, 0, 0.2) 0px 8px 10px -5px;">
                                <a href="#" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; background-color: transparent; color: rgb(105, 80, 162); text-decoration: none; transition: 0.3s ease; display: block;" title="GUEST POST: Successful parent and teacher relationships for children with autism">
                                <img alt="communication widgit asd teacher" class="attachment-hestia-blog size-hestia-blog wp-post-image" height="240" sizes="(max-width: 360px) 100vw, 360px" src="https://i0.wp.com/asdteacher.com/wp-content/uploads/2018/05/communication-widgit-asd-teacher.png?resize=360%2C240" srcset="https://i0.wp.com/asdteacher.com/wp-content/uploads/2018/05/communication-widgit-asd-teacher.png?resize=360%2C240 360w, https://i0.wp.com/asdteacher.com/wp-content/uploads/2018/05/communication-widgit-asd-teacher.png?zoom=2&amp;resize=360%2C240 720w" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; border: 0px; vertical-align: middle; max-width: 100%; height: 240px; width: 360px; border-radius: 3px; margin: 0px !important; transition: 1s ease-out;" width="360" /></a></div>
                            <div class="content" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; padding: 15px 5px;">
                                <h6 class="category" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.618; color: rgb(153, 153, 153); margin-top: 10px; margin-bottom: 10px; font-size: 12px; text-transform: uppercase;">&nbsp;</h6>
                                <h4 class="card-title" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; font-family: &quot;Roboto Slab&quot;, &quot;Times New Roman&quot;, serif; font-weight: 700; line-height: 1.4; color: rgb(60, 72, 88); margin-top: 5px; margin-bottom: 10px; font-size: 18px; text-decoration: none; word-wrap: break-word;"><a class="blog-item-title-link" href="http://asdteacher.com/successful-autism-parent-and-teacher-relationships-parent-and-teacher-perspectives/" rel="bookmark" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; background-color: transparent; color: rgb(60, 72, 88); text-decoration: none; transition: 0.3s ease; word-wrap: break-word;" title="GUEST POST: Successful parent and teacher relationships for children with autism">GUEST POST: Successful parent and teacher relationships for children with autism</a></h4>
                                <p class="card-description" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 0px 0px 10px; font-size: 14px; color: rgb(153, 153, 153);">
                                    Parent Perspective (Written by Harshita Patel, parent and author of ‘Autism in the City’)&nbsp;&nbsp; It’s Good to Talk! The moment a child with special needs comes into your life, the paperwork pours in.</p>
                            </div>
                        </div>
                    </article>
                    <span>&nbsp;</span><article class="col-xs-12 col-ms-10 col-ms-offset-1 col-sm-8 col-sm-offset-2 col-md-4 hestia-blog-item" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; display: inline-block; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float: none !important; width: 390px; margin-left: -4px; text-align: left; margin-right: -4px; vertical-align: top;">
                        <div class="card card-plain card-blog" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; display: inline-block; position: relative; width: 360px; margin-bottom: 30px; border-radius: 6px; color: rgba(0, 0, 0, 0.87); background: transparent; box-shadow: none; margin-top: 30px;">
                            <div class="card-image" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; overflow: hidden; position: relative; height: 240px; margin: 0px; border-radius: 3px; transition: all 300ms cubic-bezier(0.34, 1.61, 0.7, 1); transform: translate(0px, 0px); box-shadow: rgba(0, 0, 0, 0.56) 0px 16px 38px -12px, rgba(0, 0, 0, 0.12) 0px 4px 25px 0px, rgba(0, 0, 0, 0.2) 0px 8px 10px -5px;">
                                <a href="#" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; background-color: transparent; color: rgb(105, 80, 162); text-decoration: none; transition: 0.3s ease; display: block;" title="Using Widgit symbols to support ASD teaching">
                                <img alt="Widgit symbols asd teacher" class="attachment-hestia-blog size-hestia-blog wp-post-image" height="240" sizes="(max-width: 360px) 100vw, 360px" src="https://i1.wp.com/asdteacher.com/wp-content/uploads/2018/04/Widgit-symbols-asd-teacher.jpg?resize=360%2C240" srcset="https://i1.wp.com/asdteacher.com/wp-content/uploads/2018/04/Widgit-symbols-asd-teacher.jpg?resize=360%2C240 360w, https://i1.wp.com/asdteacher.com/wp-content/uploads/2018/04/Widgit-symbols-asd-teacher.jpg?zoom=2&amp;resize=360%2C240 720w, https://i1.wp.com/asdteacher.com/wp-content/uploads/2018/04/Widgit-symbols-asd-teacher.jpg?zoom=3&amp;resize=360%2C240 1080w" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; border: 0px; vertical-align: middle; max-width: 100%; height: 240px; width: 360px; border-radius: 3px; margin: 0px !important; transition: 1s ease-out;" width="360" /></a></div>
                            <div class="content" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; padding: 15px 5px;">
                                <h6 class="category" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.618; color: rgb(153, 153, 153); margin-top: 10px; margin-bottom: 10px; font-size: 12px; text-transform: uppercase;"><a href="http://asdteacher.com/category/blog-posts/" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; background-color: transparent; color: rgb(244, 67, 54); text-decoration: none; transition: 0.3s ease;" title="View all posts in Blog Posts">BLOG POSTS</a></h6>
                                <h4 class="card-title" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; font-family: &quot;Roboto Slab&quot;, &quot;Times New Roman&quot;, serif; font-weight: 700; line-height: 1.4; color: rgb(60, 72, 88); margin-top: 5px; margin-bottom: 10px; font-size: 18px; text-decoration: none; word-wrap: break-word;"><a class="blog-item-title-link" href="http://asdteacher.com/widgit-guest-article-using-symbols-to-support-asd-teaching/" rel="bookmark" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; background-color: transparent; color: rgb(60, 72, 88); text-decoration: none; transition: 0.3s ease; word-wrap: break-word;" title="Using Widgit symbols to support ASD teaching">Using Widgit symbols to support ASD teaching</a></h4>
                                <p class="card-description" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 0px 0px 10px; font-size: 14px; color: rgb(153, 153, 153);">
                                    I recently wrote an article for Widgit, all about ‘Using symbols to support ASD Teaching‘.&nbsp;&nbsp; Widgit is a symbol set containing more than 17,000 symbols. Widgit symbols are clear, simple, colourful and display a beautiful mind.</p>
                            </div>
                        </div>
                    </article>
                </div>
                <div class="row" data-aos="fade-up" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin-left: -15px; margin-right: -15px; text-align: center; color: rgb(60, 72, 88); font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <article class="col-xs-12 col-ms-10 col-ms-offset-1 col-sm-8 col-sm-offset-2 col-md-4 hestia-blog-item" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; display: inline-block; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float: none !important; width: 390px; margin-left: -4px; text-align: left; margin-right: -4px; vertical-align: top;">
                        <div class="card card-plain card-blog" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; display: inline-block; position: relative; width: 360px; margin-bottom: 30px; border-radius: 6px; color: rgba(0, 0, 0, 0.87); background: transparent; box-shadow: none; margin-top: 30px;">
                            <div class="card-image" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; overflow: hidden; position: relative; height: 240px; margin: 0px; border-radius: 3px; transition: all 300ms cubic-bezier(0.34, 1.61, 0.7, 1); transform: translate(0px, 0px); box-shadow: rgba(0, 0, 0, 0.56) 0px 16px 38px -12px, rgba(0, 0, 0, 0.12) 0px 4px 25px 0px, rgba(0, 0, 0, 0.2) 0px 8px 10px -5px;">
                                <a href="#" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; background-color: transparent; color: rgb(105, 80, 162); text-decoration: none; transition: 0.3s ease; display: block;" title="Teaching how to play the keyboard using colours">
                                <img alt="keyboard ASD Teacher" class="attachment-hestia-blog size-hestia-blog wp-post-image" height="240" sizes="(max-width: 360px) 100vw, 360px" src="https://i0.wp.com/asdteacher.com/wp-content/uploads/2018/03/keyboard-ASD-Teacher.png?resize=360%2C240" srcset="https://i0.wp.com/asdteacher.com/wp-content/uploads/2018/03/keyboard-ASD-Teacher.png?resize=360%2C240 360w, https://i0.wp.com/asdteacher.com/wp-content/uploads/2018/03/keyboard-ASD-Teacher.png?zoom=2&amp;resize=360%2C240 720w" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; border: 0px; vertical-align: middle; max-width: 100%; height: 240px; width: 360px; border-radius: 3px; margin: 0px !important; transition: 1s ease-out;" width="360" /></a></div>
                            <div class="content" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; padding: 15px 5px;">
                                <h6 class="category" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.618; color: rgb(153, 153, 153); margin-top: 10px; margin-bottom: 10px; font-size: 12px; text-transform: uppercase;">&nbsp;</h6>
                                <h4 class="card-title" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; font-family: &quot;Roboto Slab&quot;, &quot;Times New Roman&quot;, serif; font-weight: 700; line-height: 1.4; color: rgb(60, 72, 88); margin-top: 5px; margin-bottom: 10px; font-size: 18px; text-decoration: none; word-wrap: break-word;"><a class="blog-item-title-link" href="http://asdteacher.com/teaching-how-to-play-the-keyboard-using-colours/" rel="bookmark" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; background-color: transparent; color: rgb(60, 72, 88); text-decoration: none; transition: 0.3s ease; word-wrap: break-word;" title="Teaching how to play the keyboard using colours">Teaching how to play the keyboard using colours</a></h4>
                                <p class="card-description" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 0px 0px 10px; font-size: 14px; color: rgb(153, 153, 153);">
                                    If a child can match colours, then they can learn to play a tune on the keyboard!&nbsp;&nbsp; I love teaching music, and teaching how to play the keyboard is really fun.</p>
                            </div>
                        </div>
                    </article>
                    <span>&nbsp;</span><article class="col-xs-12 col-ms-10 col-ms-offset-1 col-sm-8 col-sm-offset-2 col-md-4 hestia-blog-item" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; display: inline-block; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float: none !important; width: 390px; margin-left: -4px; text-align: left; margin-right: -4px; vertical-align: top;">
                        <div class="card card-plain card-blog" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; display: inline-block; position: relative; width: 360px; margin-bottom: 30px; border-radius: 6px; color: rgba(0, 0, 0, 0.87); background: transparent; box-shadow: none; margin-top: 30px;">
                            <div class="card-image" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; overflow: hidden; position: relative; height: 240px; margin: 0px; border-radius: 3px; transition: all 300ms cubic-bezier(0.34, 1.61, 0.7, 1); transform: translate(0px, 0px); box-shadow: rgba(0, 0, 0, 0.56) 0px 16px 38px -12px, rgba(0, 0, 0, 0.12) 0px 4px 25px 0px, rgba(0, 0, 0, 0.2) 0px 8px 10px -5px;">
                                <a href="#" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; background-color: transparent; color: rgb(105, 80, 162); text-decoration: none; transition: 0.3s ease; display: block;" title="Sensory equipment for children with autism">
                                <img alt="ear defenders Edz ASD Teacher" class="attachment-hestia-blog size-hestia-blog wp-post-image" height="240" src="https://i0.wp.com/asdteacher.com/wp-content/uploads/2018/02/ear-defenders-Edz-ASD-Teacher.png?resize=360%2C240" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; border: 0px; vertical-align: middle; max-width: 100%; height: 240px; width: 360px; border-radius: 3px; margin: 0px !important; transition: 1s ease-out;" width="360" /></a></div>
                            <div class="content" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; padding: 15px 5px;">
                                <h6 class="category" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.618; color: rgb(153, 153, 153); margin-top: 10px; margin-bottom: 10px; font-size: 12px; text-transform: uppercase;">&nbsp;</h6>
                                <h4 class="card-title" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; font-family: &quot;Roboto Slab&quot;, &quot;Times New Roman&quot;, serif; font-weight: 700; line-height: 1.4; color: rgb(60, 72, 88); margin-top: 5px; margin-bottom: 10px; font-size: 18px; text-decoration: none; word-wrap: break-word;"><a class="blog-item-title-link" href="http://asdteacher.com/sensory-equipment-children-autism/" rel="bookmark" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; background-color: transparent; color: rgb(60, 72, 88); text-decoration: none; transition: 0.3s ease; word-wrap: break-word;" title="Sensory equipment for children with autism">Sensory equipment for children with autism</a></h4>
                                <p class="card-description" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 0px 0px 10px; font-size: 14px; color: rgb(153, 153, 153);">
                                    As a teacher, I have used a range of sensory equipment in the classroom to support individual sensory needs.&nbsp;&nbsp; An Occupational Therapist (OT) is the professional who can support you to assess the sensory.</p>
                            </div>
                        </div>
                    </article>
                    <span>&nbsp;</span><article class="col-xs-12 col-ms-10 col-ms-offset-1 col-sm-8 col-sm-offset-2 col-md-4 hestia-blog-item" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; display: inline-block; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float: none !important; width: 390px; margin-left: -4px; text-align: left; margin-right: -4px; vertical-align: top;">
                        <div class="card card-plain card-blog" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; display: inline-block; position: relative; width: 360px; margin-bottom: 30px; border-radius: 6px; color: rgba(0, 0, 0, 0.87); background: transparent; box-shadow: none; margin-top: 30px;">
                            <div class="card-image" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; overflow: hidden; position: relative; height: 240px; margin: 0px; border-radius: 3px; transition: all 300ms cubic-bezier(0.34, 1.61, 0.7, 1); transform: translate(0px, 0px); box-shadow: rgba(0, 0, 0, 0.56) 0px 16px 38px -12px, rgba(0, 0, 0, 0.12) 0px 4px 25px 0px, rgba(0, 0, 0, 0.2) 0px 8px 10px -5px;">
                                <a href="#" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; background-color: transparent; color: rgb(105, 80, 162); text-decoration: none; transition: 0.3s ease; display: block;" title="Emotional regulation: Teaching children with autism to recognise and respond to their emotion">
                                <img alt="emotion response visual support asd teacher" class="attachment-hestia-blog size-hestia-blog wp-post-image" height="240" sizes="(max-width: 360px) 100vw, 360px" src="https://i0.wp.com/asdteacher.com/wp-content/uploads/2018/02/emotion-response-visual-support-asd-teacher.jpg?resize=360%2C240" srcset="https://i0.wp.com/asdteacher.com/wp-content/uploads/2018/02/emotion-response-visual-support-asd-teacher.jpg?resize=360%2C240 360w, https://i0.wp.com/asdteacher.com/wp-content/uploads/2018/02/emotion-response-visual-support-asd-teacher.jpg?zoom=2&amp;resize=360%2C240 720w, https://i0.wp.com/asdteacher.com/wp-content/uploads/2018/02/emotion-response-visual-support-asd-teacher.jpg?zoom=3&amp;resize=360%2C240 1080w" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; border: 0px; vertical-align: middle; max-width: 100%; height: 240px; width: 360px; border-radius: 3px; margin: 0px !important; transition: 1s ease-out;" width="360" /></a></div>
                            <div class="content" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; padding: 15px 5px;">
                                <h6 class="category" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.618; color: rgb(153, 153, 153); margin-top: 10px; margin-bottom: 10px; font-size: 12px; text-transform: uppercase;">&nbsp;</h6>
                                <h4 class="card-title" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; font-family: &quot;Roboto Slab&quot;, &quot;Times New Roman&quot;, serif; font-weight: 700; line-height: 1.4; color: rgb(60, 72, 88); margin-top: 5px; margin-bottom: 10px; font-size: 18px; text-decoration: none; word-wrap: break-word;"><a class="blog-item-title-link" href="http://asdteacher.com/emotional-regulation-teaching-children-autism-recognise-respond-emotion/" rel="bookmark" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; background-color: transparent; color: rgb(60, 72, 88); text-decoration: none; transition: 0.3s ease; word-wrap: break-word;" title="Emotional regulation: Teaching children with autism to recognise and respond to their emotion">Emotional regulation: Teaching children with autism to recognise and respond to their emotion</a></h4>
                                <p class="card-description" style="box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 0px 0px 10px; font-size: 14px; color: rgb(153, 153, 153);">
                                    Emotional regulation is a key area of development.&nbsp;&nbsp; Being able to emotionally regulate means being able&nbsp;to effectively manage and respond to an emotional experience&nbsp;&nbsp; For children with autism, understanding emotion and knowing how to mix with them.</p>
                            </div>
                        </div>
                    </article>
                </div>
            </td>
        </tr>
    </table>
</asp:Content>

